#!/bin/bash

if [ -z "$1" ]; then
    echo "$0 [json file]"
    exit 1
fi

if [[ "$OSTYPE" == "darwin"* ]]; then
    # Mac OSX xargs is shit apparently
    jq -r "keys[]" "$1" | fzf -m --print0 | xargs -0 -I {} jq ".[\"{}\"]" "$1" | jq -s . --compact-output
else
    jq -r "keys[]" "$1" | fzf -m --print0 | xargs -r -0 -I {} jq ".[\"{}\"]" "$1" | jq -s . --compact-output
fi
