#!/bin/bash

set -e
set -o pipefail

DOMAIN="https://samsara.youearnedit.com"

if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ] || [ -z "$4" ]; then
    echo "$0 [message] [points] [to-ids] [session]"
    exit 1
fi

message="$1"
points="$2"
to="$3"
session="$4"

json="{\"company_tag_id\":\"\",\"message\":\"$message\",\"points\":\"$points\",\"privacy\":\"public\",\"to_ids\":$to,\"skills\":[],\"expand\":[\"from\"]}"

curl -s --cookie "_session_id=$session" $DOMAIN/posts \
    | grep csrf-token \
    | sed 's/^.*content="\(.*\)".*$/\1/' \
    | xargs -I {} \
        curl -s $DOMAIN/api/v3/posts/ \
            --data "$json" \
            --cookie "_session_id=$session" \
            -H "X-CSRF-Token: {}" \
            -H "Content-Type: application/json" \
            -H "Origin: $DOMAIN" \
    | jq --raw-output \
        "(select(.from != null) | \
        \"Success! \(.from.giving_balance) points remaining.\"), \
        (select(.errors != null) | {errors})"
